# -*- coding: utf-8 -*-
"""apples_stock_forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PGDFYKU6NDOPd0kpg9Wlnst0v0ntdP2
"""



# APPLE STOCK PRICE FORECASTING (Final Streamlit Version)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from sklearn.metrics import mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor
from statsmodels.tsa.arima.model import ARIMA
import os

# Streamlit Page Settings
st.set_page_config(page_title="📈 Apple Stock Forecasting", layout="wide")

st.title(" Apple Stock Price Forecasting App")
st.markdown("Upload your dataset (or use the default one) to explore Apple stock trends, run EDA, and forecast prices!")

# ----------- File Upload Section -----------
default_path = "Apples_stock.xlsx"

uploaded_file = st.file_uploader("Upload your Excel file", type=["xlsx"])

if uploaded_file is not None:
    df = pd.read_excel(uploaded_file)
    st.success("Custom file uploaded successfully!")
elif os.path.exists(default_path):
    df = pd.read_excel(default_path)
    st.info("Using default dataset: **Apples_stock.xlsx**")
else:
    st.warning(" Please upload your Excel file to continue.")
    st.stop()

# ----------- Show Preview -----------
st.write("###  Data Preview")
st.dataframe(df.head())
st.write(f"**Dataset Shape:** {df.shape}")

# ----------- Data Cleaning -----------
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df['timestamp'] = pd.to_datetime(df['timestamp'])
df['hour'] = df['timestamp'].dt.hour
df['weekday'] = df['timestamp'].dt.weekday

# Filter (Weekdays 4AM–8PM)
filtered_df = df[
    (df['hour'] >= 4) &
    (df['hour'] <= 20) &
    (df['weekday'] < 5)
].copy()
filtered_df.drop(['hour', 'weekday'], axis=1, inplace=True)

st.write("###  Cleaned and Filtered Data")
st.dataframe(filtered_df.head())

# ----------- EDA Section -----------
if st.checkbox(" Show EDA (Exploratory Data Analysis)"):
    st.subheader("Stock Price Over Time")
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(filtered_df['timestamp'], filtered_df['stock_price'], color='blue')
    ax.set_title("Apple Stock Price Over Time (Weekdays 4AM–8PM)")
    ax.set_xlabel("Timestamp")
    ax.set_ylabel("Stock Price")
    ax.grid(True)
    st.pyplot(fig)

    st.subheader("Correlation Heatmap")
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(filtered_df.corr(), annot=True, cmap='coolwarm', ax=ax)
    st.pyplot(fig)

    st.subheader("Correlation with Stock Price")
    st.dataframe(filtered_df.corr()['stock_price'].sort_values(ascending=False))

    st.subheader("Pairplot of Key Indicators")
    sns.pairplot(filtered_df[['stock_price', 'nasdaq_index', 'sp500_index',
                              'inflation_rate', 'unemployment_rate',
                              'interest_rate', 'market_sentiment']])
    st.pyplot(plt)

# ----------- Outlier Removal Section -----------
if st.checkbox(" Show Outlier Removal"):
    cols = ['stock_price', 'nasdaq_index', 'sp500_index', 'inflation_rate',
            'unemployment_rate', 'interest_rate', 'market_sentiment']
    cleaned_df = filtered_df.copy()
    for col in cols:
        Q1 = cleaned_df[col].quantile(0.25)
        Q3 = cleaned_df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        cleaned_df = cleaned_df[(cleaned_df[col] >= lower_bound) & (cleaned_df[col] <= upper_bound)]

    st.success(f" Outliers Removed — New Shape: {cleaned_df.shape}")
    st.dataframe(cleaned_df.head())

    st.subheader("Boxplots After Cleaning")
    for col in cols:
        fig, ax = plt.subplots(figsize=(6, 3))
        sns.boxplot(x=cleaned_df[col], color='lightgreen', ax=ax)
        st.pyplot(fig)

# ----------- Model Building -----------
if st.button(" Run XGBoost Model"):
    target_col = 'stock_price'
    data = df.copy()

    # Feature Engineering
    for lag in range(1, 8):
        data[f'lag_{lag}'] = data[target_col].shift(lag)
    data['roll_mean_7'] = data[target_col].rolling(window=7).mean().shift(1)
    data.dropna(inplace=True)

    X = data.drop(columns=[target_col])
    y = data[target_col]
    train_X, test_X = X[:-30], X[-30:]
    train_y, test_y = y[:-30], y[-30:]

    model = XGBRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )
    model.fit(train_X.drop(columns=['timestamp']), train_y)
    pred = model.predict(test_X.drop(columns=['timestamp']))

    rmse = mean_squared_error(test_y, pred)**0.5
    mae = mean_absolute_error(test_y, pred)

    st.subheader("Model Performance")
    st.write(f"**RMSE:** {rmse:.2f}")
    st.write(f"**MAE:** {mae:.2f}")

    st.subheader("Actual vs Predicted Prices")
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(train_y.index, train_y, label='Training', color='blue')
    ax.plot(test_y.index, test_y, label='Actual', color='black')
    ax.plot(test_y.index, pred, label='Predicted', color='green', linestyle='--')
    ax.legend()
    ax.grid(True)
    st.pyplot(fig)

    # ----------- Forecast Next 30 Days -----------
    future_preds = []
    last_row = data.iloc[-1:].copy()
    for i in range(30):
        next_pred = model.predict(last_row.drop(columns=[target_col, 'timestamp'], errors='ignore'))[0]
        future_preds.append(next_pred)
        new_row = last_row.copy()
        for lag in range(7, 1, -1):
            new_row[f'lag_{lag}'] = new_row[f'lag_{lag-1}']
        new_row['lag_1'] = next_pred
        new_row['roll_mean_7'] = new_row[[f'lag_{i}' for i in range(1, 8)]].mean(axis=1)
        last_row = new_row

    future_df = pd.DataFrame({'Day': np.arange(1, 31), 'Predicted Price': future_preds})
    st.subheader(" Next 30-Day Forecast")
    st.dataframe(future_df)

    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(future_df['Day'], future_df['Predicted Price'], marker='o', color='purple')
    ax.set_title("Next 30 Days Predicted Apple Stock Prices")
    ax.set_xlabel("Days Ahead")
    ax.set_ylabel("Predicted Stock Price")
    st.pyplot(fig)

    # Download forecast
    csv = future_df.to_csv(index=False).encode('utf-8')
    st.download_button("⬇ Download Forecast as CSV", data=csv, file_name="apple_stock_forecast.csv")